# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python
sudo: true
dist: xenial

matrix:
  include:
      - python: 3.6
      - python: 3.7


before_install:
  - uname -a
  - free -m
  - df -h
  - pip -V
  - ulimit -a

install:
  - sudo apt-get install npm
  - sudo npm install -g less
  - pip install -r requirements/travis.txt

before_script:

script:
  - flask test --coverage

notifications:
  email: false

after_success:
  - codecov