# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python
sudo: true
dist: xenial

services:
  - mongodb

matrix:
  include:
      - python: 3.6
      - python: 3.7

before_install:
  - uname -a
  - free -m
  - df -h
  - pip -V
  - ulimit -a

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - sudo apt-get install npm
  - sudo npm install
  - conda create -n qca_web -c rdkit rdkit python=$TRAVIS_PYTHON_VERSION
  - conda activate qca_web
  - pip install -r requirements/travis.txt
  - pip install pytest-cov codecov

before_script:
  - sleep 15    # fixes an issue with travis,
                # MongoDB does not accept connections immediately.
  - mongo test_qca_db --eval ';' # --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - pytest -v --cov=app/ --durations=5

notifications:
  email: false

after_success:
  - codecov