name: qca_web
channels:
  - conda-forge
  - rdkit
dependencies:
  - python=3.7
  - pip=19.3
  - rdkit
# Test depends
  - codecov
  - pytest
  - pytest-cov
  - requests-mock
  - pip:
    - -r requirements.txt
