name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
        #  schedule:
        #    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"]
        node-version: ["14.x"]
        mongodb-version: ["4.x"]
        environ: [qca_web]

    steps:
      - uses: actions/checkout@v2
      - name: Additional info about the build
        run: |
          uname -a
          free -m
          df -h
          pip -V
          ulimit -a

      - name: Configure conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: ${{ matrix.environ }}
          environment-file: environment.yml
          auto-activate-base: false

      - name: Environment Information
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Setting up dependencies (Node.js)
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Install Node.js 
        run: |
          npm install

      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.3.0

      - name: Key component versions
        shell: bash -l {0}
        run: |
          mongod --version
          mongo test_qca_db --eval ';'

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest -v -rsx --cov=app tests/ --tb=short --cov-report=xml

      - name: Code coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
